version: '3'
services:
  nginx:
    image: nginx:1.12.2-alpine
    ports:
      - "80:80"
    depends_on:
      - php72
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./public:/var/www/public

  php72:
    image: php:7.2.4-fpm-alpine
    volumes:
      - ./public:/var/www/public
