version: '3'
services:
  nginx:
    image: nginx:1.12.2-alpine
    ports:
      - "80:80"
    depends_on:
      - php72
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./public:/var/www/public

  php72:
    build: ./docker/php72
    env_file: docker/mysql/.env
    environment:
      DATABASE_HOST: db
    depends_on:
        - db
    volumes:
      - ./public:/var/www/public

  db:
    image: mysql:5.7.21
    env_file: docker/mysql/.env
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
      - ./docker/mysql/files/default.sql:/docker-entrypoint-initdb.d/default.sql

volumes:
  db-data:
